### PR TITLE
feat: Add railway template for kuai mvp DApp

### PR DESCRIPTION
**Pull request by yanguoyu**
We can visit the deployment at https://kuai-mvp-dapp-ui-production.up.railway.app.

### CODE REVIEW

**Review by Daryl-L — APPROVED** [review]

**Comment by Keith-CY** [comment]
image
It warns that `repo name` conflicts, is there a way to fork and deploy?

**Comment by yanguoyu** [comment]
> image It warns that `repo name` conflicts, is there a way to fork and deploy?

Because you have forked `kuai`, renaming `kuai` to another name can fork deploy success.

**Comment by Keith-CY** [comment]
> > image It warns that `repo name` conflicts, is there a way to fork and deploy?
> 
> Because you have forked `kuai`, renaming `kuai` to another name can fork deploy success.

I've removed the forked one several days ago, and the <kbd>fork</kbd> is available now
image

**Comment by yanguoyu** [comment]
image
image

Here you should select your repo, but not `ckb-js` org.

**Review by Keith-CY — APPROVED** [review]

**Pull request merged**
