### PR TITLE
feat: add coverage action

### PR DESCRIPTION
**Pull request by PainterPuppets**
- support coverage action

#200

### CODE REVIEW

**Comment by Keith-CY** [comment]
CI failed

**Comment by Keith-CY** [comment]
How is it going

**Comment by Keith-CY** [comment]
How is it going

**Comment by Keith-CY** [comment]
The action has been executed at https://github.com/ckb-js/kuai/actions/runs/4930573627/jobs/8811640162 and the report can be found at https://app.codecov.io/github/ckb-js/kuai/commit/2181467b024c762ad551c2f310054598f0be2b84

Can we set the report be attached in the PR automatically?

**Comment by Keith-CY** [comment]
What if exclude tests in `packages/samples` from the coverage

**Review by Keith-CY — APPROVED** [review]

**Comment by PainterPuppets** [comment]
> The action has been executed at https://github.com/ckb-js/kuai/actions/runs/4930573627/jobs/8811640162 and the report can be found at https://app.codecov.io/github/ckb-js/kuai/commit/2181467b024c762ad551c2f310054598f0be2b84
> 
> Can we set the report be attached in the PR automatically?

Ok, I'll see how to do it

**Review by yanguoyu — APPROVED** [review]

**Pull request merged**
